var searchData=
[
  ['v_20tag_20push_0',['8.3 Release flow (what happens on a &lt;span class=&quot;tt&quot;&gt;v*&lt;/span&gt; tag push)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md148',1,'']]],
  ['v0_200_201_20→_20current_20v0_200_204_1',['6.4 Release asset delta (MangaD &lt;span class=&quot;tt&quot;&gt;v0.0.1&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;v0.0.4&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md125',1,'']]],
  ['v0_200_2010_2',['17.7 Release evidence — &lt;span class=&quot;tt&quot;&gt;v0.0.10&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md199',1,'']]],
  ['v0_200_204_3',['6.4 Release asset delta (MangaD &lt;span class=&quot;tt&quot;&gt;v0.0.1&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;v0.0.4&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md125',1,'']]],
  ['v0_200_209_4',['v0 0 9',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md169',1,'13.2 New policy (current, &lt;span class=&quot;tt&quot;&gt;v0.0.9&lt;/span&gt;)'],['../md_docs_2AUDIT.html#autotoc_md10',1,'5. Current distribution inventory — v0.0.9'],['../md_docs_2distribution-hardening-evidence.html#autotoc_md325',1,'Baseline release contract (live, &lt;span class=&quot;tt&quot;&gt;v0.0.9&lt;/span&gt;)']]],
  ['v0_200_209_20github_20validation_5',['v0.0.9 GitHub validation',['../md_docs_2AUDIT.html#autotoc_md66',1,'']]],
  ['valgrind_6',['Valgrind',['../md_docs_2development__guide.html#autotoc_md297',1,'']]],
  ['validation_7',['13.6 Validation',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md173',1,'']]],
  ['validation_8',['validation',['../md_docs_2TASKS.html#autotoc_md240',1,'21. Artifact structural validation'],['../md_docs_2AUDIT.html#autotoc_md81',1,'22. Required future artifact validation'],['../md_docs_2AUDIT.html#autotoc_md65',1,'Repository/static validation'],['../md_docs_2AUDIT.html#autotoc_md67',1,'Round 2 artifact-level validation'],['../md_docs_2AUDIT.html#autotoc_md66',1,'v0.0.9 GitHub validation']]],
  ['validation_202026_2009_2025_9',['PASS 1-3 — Implementation and local validation (2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md328',1,'']]],
  ['validation_20and_20qa_10',['P1 — Artifact validation and QA',['../md_docs_2TASKS.html#autotoc_md239',1,'']]],
  ['validation_20commands_20→_20actual_20result_11',['Validation (commands → actual result)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md336',1,'']]],
  ['validation_20evidence_12',['21. Validation evidence',['../md_docs_2AUDIT.html#autotoc_md64',1,'']]],
  ['validation_20performed_13',['Validation performed',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md188',1,'16.7 Validation performed'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md198',1,'17.6 Validation performed']]],
  ['validation_20results_20commands_20→_20output_14',['Validation results (commands → output)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md330',1,'']]],
  ['variants_15',['11.3 Q: Are there benefits to compiling across all these compiler variants?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md158',1,'']]],
  ['vcpkg_16',['vcpkg',['../md_docs_2install.html#autotoc_md352',1,'Google Test (manual install not recommended, prefer vcpkg)'],['../md_docs_2install.html#autotoc_md351',1,'wxWidgets (manual install not recommended, prefer vcpkg)']]],
  ['vcpkg_20binary_20cache_20contract_20adr_20006_202026_2009_2025_17',['PASS 4 — vcpkg binary-cache contract (ADR 006, 2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md333',1,'']]],
  ['vcpkg_20default_20packagemanager_20cmake_20d9_20rationale_18',['7.9 D9 — Dual package manager, vcpkg default (&lt;span class=&quot;tt&quot;&gt;PackageManager.cmake&lt;/span&gt; + D9 rationale)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md137',1,'']]],
  ['vcpkg_20recommended_19',['vcpkg (recommended)',['../md_docs_2install.html#autotoc_md353',1,'']]],
  ['verification_20',['verification',['../md_docs_2AUDIT.html#autotoc_md72',1,'21A. Round 3 — complete tracked-snapshot verification'],['../md_docs_2TASKS.html#autotoc_md246',1,'25. Rebuild verification'],['../md_docs_2TASKS.html#autotoc_md274',1,'43. Continuous verification']]],
  ['verification_20is_20not_20uniform_21',['Architecture verification is not uniform',['../md_docs_2AUDIT.html#autotoc_md34',1,'']]],
  ['verification_20ledger_20evidence_20cited_20in_20this_20document_22',['14. Verification Ledger (evidence cited in this document)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md177',1,'']]],
  ['verification_20toolkit_23',['46. Consumer verification toolkit',['../md_docs_2TASKS.html#autotoc_md278',1,'']]],
  ['version_20contract_24',['1. Single release identity and version contract',['../md_docs_2TASKS.html#autotoc_md210',1,'']]],
  ['version_20resolution_20anchor_25',['7.12 D12 — Single version resolution anchor',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md140',1,'']]],
  ['version_20resolution_20occurs_20too_20late_26',['Critical: GitHub release version resolution occurs too late',['../md_docs_2AUDIT.html#autotoc_md75',1,'']]],
  ['versioning_27',['Versioning',['../md_docs_2development__guide.html#autotoc_md316',1,'']]],
  ['vex_20handling_28',['49. Security advisory and VEX handling',['../md_docs_2TASKS.html#autotoc_md281',1,'']]],
  ['view_29',['8. How the Project Works Now (Operational View)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md145',1,'']]],
  ['visible_20from_20history_30',['4.3 Trade-offs visible from history',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md115',1,'']]],
  ['vs_20current_31',['6. Comparative Deep-Dive: Original vs Current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md121',1,'']]],
  ['vs_20current_32',['6.3 Workflow inventory: original vs current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md124',1,'']]],
  ['vs_20dynamic_20crt_20on_20windows_33',['vs dynamic CRT on Windows',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md162',1,'12.2 Static vs. dynamic CRT on Windows'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md138',1,'7.10 D10 — Static vs dynamic CRT on Windows']]],
  ['vs_20target_20matrix_34',['6. Current vs target matrix',['../md_docs_2AUDIT.html#autotoc_md16',1,'']]]
];
