var searchData=
[
  ['s_20pass_20introduced_20the_20durable_20core_0',['4.1 What NaylaCruz&apos;s pass introduced (the durable core)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md13',1,'']]],
  ['sanitizers_1',['Sanitizers',['../md_docs_2development__guide.html#autotoc_md228',1,'']]],
  ['satisfied_2',['20.5 Isolation guarantees (§6 of the issue, satisfied)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md124',1,'']]],
  ['sbom_3',['27. SBOM',['../md_docs_2TASKS.html#autotoc_md180',1,'']]],
  ['sbom_20provenance_20attestations_20and_20supply_20chain_20controls_4',['P1 — SBOM, provenance, attestations, and supply-chain controls',['../md_docs_2TASKS.html#autotoc_md178',1,'']]],
  ['scope_20unless_20separately_20justified_5',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md215',1,'']]],
  ['sdx_20cpp_20project_20template_6',['5. The Current Fork: &lt;span class=&quot;tt&quot;&gt;Jackie-SDX/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md17',1,'']]],
  ['section_7',['17.10 Evidence ledger for this section',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md102',1,'']]],
  ['security_8',['31. GitLab parity and security',['../md_docs_2TASKS.html#autotoc_md186',1,'']]],
  ['security_20advisory_20and_20vex_20handling_9',['49. Security advisory and VEX handling',['../md_docs_2TASKS.html#autotoc_md211',1,'']]],
  ['security_20and_20governance_10',['P1 — CI/CD security and governance',['../md_docs_2TASKS.html#autotoc_md184',1,'']]],
  ['security_20support_20policy_11',['38. Security/support policy',['../md_docs_2TASKS.html#autotoc_md197',1,'']]],
  ['security_20testing_20of_20the_20release_20path_12',['47. Security testing of the release path',['../md_docs_2TASKS.html#autotoc_md209',1,'']]],
  ['selection_20—_20the_20exact_20user_20steps_13',['20.4 Manager selection — the exact user steps',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['selection_20vcpkg_20conan_202_14',['Package manager selection (vcpkg / Conan 2)',['../md_docs_2install.html#autotoc_md285',1,'']]],
  ['semantics_15',['7. Release-critical CI failure semantics',['../md_docs_2TASKS.html#autotoc_md146',1,'']]],
  ['separately_20justified_16',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md215',1,'']]],
  ['separation_20of_20release_20workflows_20adr_20005_20ci_20yml_17',['7.2 D2 — Strict separation of release workflows (&lt;span class=&quot;tt&quot;&gt;ADR 005&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;ci.yml&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md30',1,'']]],
  ['session_20record_202026_2009_2023_18',['13. Release Archive Policy — Session Record (2026-09-23)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md67',1,'']]],
  ['shas_20adr_20003_19',['7.6 D6 — Pin third-party actions to commit SHAs (&lt;span class=&quot;tt&quot;&gt;ADR 003&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md34',1,'']]],
  ['signing_20',['Signing',['../md_docs_2development__guide.html#autotoc_md248',1,'']]],
  ['signing_20key_20management_21',['29. Signing-key management',['../md_docs_2TASKS.html#autotoc_md182',1,'']]],
  ['single_20release_20identity_20and_20version_20contract_22',['1. Single release identity and version contract',['../md_docs_2TASKS.html#autotoc_md140',1,'']]],
  ['single_20source_20of_20build_20truth_20adr_20001_23',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md35',1,'']]],
  ['single_20version_20resolution_20anchor_24',['7.12 D12 — Single version resolution anchor',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md40',1,'']]],
  ['source_20level_20changes_20worth_20calling_20out_25',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md23',1,'']]],
  ['source_20of_20build_20truth_20adr_20001_26',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md35',1,'']]],
  ['staging_20lane_27',['7.14 D14 — Experimental staging lane',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md42',1,'']]],
  ['stale_20branch_20cleanup_20executed_202026_2009_2025_28',['17.8 Stale-branch cleanup (executed 2026-09-25)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md100',1,'']]],
  ['started_29',['Started',['../md_docs_2getting__started.html',1,'Getting Started'],['../index.html#autotoc_md310',1,'Getting Started']]],
  ['state_20on_20main_2096240c0_30',['5.1 State on &lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md18',1,'']]],
  ['static_20analysis_31',['Static analysis',['../md_docs_2development__guide.html#autotoc_md221',1,'']]],
  ['static_20vs_20dynamic_20crt_20on_20windows_32',['Static vs dynamic CRT on Windows',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md62',1,'12.2 Static vs. dynamic CRT on Windows'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md38',1,'7.10 D10 — Static vs dynamic CRT on Windows']]],
  ['status_33',['Progress status',['../index.html#autotoc_md308',1,'']]],
  ['steps_34',['20.4 Manager selection — the exact user steps',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['still_20runner_20credential_20dependent_20cannot_20be_20claimed_20green_20yet_35',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md261',1,'']]],
  ['strategy_36',['42. Update and distribution strategy',['../md_docs_2TASKS.html#autotoc_md203',1,'']]],
  ['strict_20separation_20of_20release_20workflows_20adr_20005_20ci_20yml_37',['7.2 D2 — Strict separation of release workflows (&lt;span class=&quot;tt&quot;&gt;ADR 005&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;ci.yml&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md30',1,'']]],
  ['structural_20validation_38',['21. Artifact structural validation',['../md_docs_2TASKS.html#autotoc_md170',1,'']]],
  ['submission_39',['7.11 D11 — Opt-in CDash instead of upstream submission',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md39',1,'']]],
  ['summary_40',['1. Executive Summary',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md2',1,'']]],
  ['summary_20of_20decisions_41',['12.1 Summary of decisions',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md61',1,'']]],
  ['supply_20chain_20controls_42',['P1 — SBOM, provenance, attestations, and supply-chain controls',['../md_docs_2TASKS.html#autotoc_md178',1,'']]],
  ['supply_20chain_20position_43',['20.6 Dependency and supply-chain position',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md125',1,'']]],
  ['support_20policy_44',['38. Security/support policy',['../md_docs_2TASKS.html#autotoc_md197',1,'']]],
  ['support_20readiness_45',['P1 — Documentation, legal, and support readiness',['../md_docs_2TASKS.html#autotoc_md194',1,'']]],
  ['system_46',['8.1 Build system',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md46',1,'']]]
];
