var searchData=
[
  ['lane_0',['7.14 D14 — Experimental staging lane',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md142',1,'']]],
  ['late_1',['Critical: GitHub release version resolution occurs too late',['../md_docs_2AUDIT.html#autotoc_md75',1,'']]],
  ['leak_20into_20uploads_2',['7.3 D3 — Release inventory manifests must never leak into uploads',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md131',1,'']]],
  ['ledger_3',['Distribution Hardening — Evidence Ledger',['../md_docs_2distribution-hardening-evidence.html',1,'']]],
  ['ledger_4',['16.9 Evidence ledger',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md190',1,'']]],
  ['ledger_20evidence_20cited_20in_20this_20document_5',['14. Verification Ledger (evidence cited in this document)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md177',1,'']]],
  ['ledger_20for_20this_20section_6',['17.10 Evidence ledger for this section',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md202',1,'']]],
  ['legal_20and_20support_20readiness_7',['P1 — Documentation, legal, and support readiness',['../md_docs_2TASKS.html#autotoc_md264',1,'']]],
  ['level_20changes_20worth_20calling_20out_8',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['level_20findings_9',['Round 3 source-level findings',['../md_docs_2AUDIT.html#autotoc_md74',1,'']]],
  ['level_20validation_10',['Round 2 artifact-level validation',['../md_docs_2AUDIT.html#autotoc_md67',1,'']]],
  ['libraries_11',['Third-Party Libraries',['../index.html#autotoc_md378',1,'']]],
  ['libraries_12',['Adding libraries',['../md_docs_2development__guide.html#autotoc_md302',1,'']]],
  ['license_13',['License',['../index.html#autotoc_md377',1,'']]],
  ['license_20and_20third_20party_20compliance_14',['37. License and third-party compliance',['../md_docs_2TASKS.html#autotoc_md266',1,'']]],
  ['licenses_15',['Licenses',['../md_docs_2development__guide.html#autotoc_md317',1,'']]],
  ['lifecycle_16',['lifecycle',['../md_docs_2TASKS.html#autotoc_md221',1,'10. NSIS lifecycle'],['../md_docs_2TASKS.html#autotoc_md222',1,'11. WiX MSI lifecycle'],['../md_docs_2TASKS.html#autotoc_md228',1,'15. macOS distribution lifecycle']]],
  ['lifecycle_20and_20user_20experience_17',['P1 — Installer/package lifecycle and user experience',['../md_docs_2TASKS.html#autotoc_md259',1,'']]],
  ['lifecycle_20matrix_18',['33. Cross-platform lifecycle matrix',['../md_docs_2TASKS.html#autotoc_md260',1,'']]],
  ['limitations_19',['Research limitations',['../md_docs_2TASKS.html#autotoc_md288',1,'']]],
  ['limitations_20of_20the_20original_20',['3.4 Known limitations of the original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md110',1,'']]],
  ['limits_21',['16.8 Residual risks and honest limits',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md189',1,'']]],
  ['limits_20and_20closed_20follow_20ups_22',['17.9 Deferred work, honest limits and closed follow-ups',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md201',1,'']]],
  ['lineage_20and_20fork_20graph_23',['2. Repository Lineage and Fork Graph',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md104',1,'']]],
  ['links_24',['Tutorial links',['../md_docs_2development__guide.html#autotoc_md308',1,'']]],
  ['linux_25',['Linux',['../md_docs_2install.html#autotoc_md344',1,'Arch Linux / Manjaro Linux'],['../md_docs_2AUDIT.html#autotoc_md46',1,'Linux'],['../md_docs_2AUDIT.html#autotoc_md97',1,'Linux'],['../md_docs_2install.html#autotoc_md343',1,'Linux']]],
  ['linux_20assessment_26',['9. Linux assessment',['../md_docs_2AUDIT.html#autotoc_md26',1,'']]],
  ['linux_20deb_27',['Linux DEB',['../md_docs_2AUDIT.html#autotoc_md84',1,'']]],
  ['linux_20deb_20rpm_20tar_20gz_20distribution_28',['P0 — Linux DEB/RPM/tar.gz distribution',['../md_docs_2TASKS.html#autotoc_md230',1,'']]],
  ['linux_20mac_29',['Linux &amp;amp; Mac',['../md_docs_2install.html#autotoc_md356',1,'']]],
  ['linux_20manjaro_20linux_30',['Arch Linux / Manjaro Linux',['../md_docs_2install.html#autotoc_md344',1,'']]],
  ['linux_20mint_20ubuntu_31',['Debian / Linux Mint / Ubuntu',['../md_docs_2install.html#autotoc_md345',1,'']]],
  ['linux_20representative_20artifact_32',['Linux representative artifact',['../md_docs_2AUDIT.html#autotoc_md68',1,'']]],
  ['linux_20rpm_33',['Linux RPM',['../md_docs_2AUDIT.html#autotoc_md85',1,'']]],
  ['linux_20tar_20gz_20—_20keep_20harden_34',['Linux tar.gz — KEEP / HARDEN',['../md_docs_2AUDIT.html#autotoc_md29',1,'']]],
  ['linux_20tarball_20correctness_35',['18. Linux tarball correctness',['../md_docs_2TASKS.html#autotoc_md233',1,'']]],
  ['linux_3a_2015_20artifacts_36',['Linux: 15 artifacts',['../md_docs_2AUDIT.html#autotoc_md12',1,'']]],
  ['live_20acceptance_20evidence_20target_20repo_20dispatches_202026_2009_2025_37',['Live acceptance evidence (target-repo dispatches, 2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md337',1,'']]],
  ['live_20v0_200_209_38',['Baseline release contract (live, &lt;span class=&quot;tt&quot;&gt;v0.0.9&lt;/span&gt;)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md325',1,'']]],
  ['llvm_20in_20the_20matrix_39',['11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md156',1,'']]],
  ['local_20validation_202026_2009_2025_40',['PASS 1-3 — Implementation and local validation (2026-09-25)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md328',1,'']]],
  ['localization_20accessibility_20readiness_41',['48. Conditional localization/accessibility readiness',['../md_docs_2TASKS.html#autotoc_md280',1,'']]],
  ['long_20term_20maintenance_42',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md270',1,'']]]
];
