var searchData=
[
  ['mac_0',['Linux &amp;amp; Mac',['../md_docs_2install.html#autotoc_md292',1,'']]],
  ['macos_1',['MacOS',['../md_docs_2install.html#autotoc_md302',1,'']]],
  ['macos_2',['macOS',['../md_docs_2install.html#autotoc_md284',1,'']]],
  ['macos_20architecture_20and_20runtime_20closure_3',['13. macOS architecture and runtime closure',['../md_docs_2TASKS.html#autotoc_md156',1,'']]],
  ['macos_20distribution_4',['P0 — macOS distribution',['../md_docs_2TASKS.html#autotoc_md154',1,'']]],
  ['macos_20distribution_20lifecycle_5',['15. macOS distribution lifecycle',['../md_docs_2TASKS.html#autotoc_md158',1,'']]],
  ['made_6',['16.3 Changes made',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md84',1,'']]],
  ['main_2046815c1_7',['20.2 Baseline, recorded before any edit (&lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; @ &lt;span class=&quot;tt&quot;&gt;46815c1&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md121',1,'']]],
  ['main_2096240c0_8',['5.1 State on &lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md18',1,'']]],
  ['maintenance_9',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md200',1,'']]],
  ['management_10',['29. Signing-key management',['../md_docs_2TASKS.html#autotoc_md182',1,'']]],
  ['manager_20in_20ci_11',['Choosing the manager in CI',['../md_docs_2install.html#autotoc_md288',1,'']]],
  ['manager_20selection_20—_20the_20exact_20user_20steps_12',['20.4 Manager selection — the exact user steps',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['manager_20selection_20vcpkg_20conan_202_13',['Package manager selection (vcpkg / Conan 2)',['../md_docs_2install.html#autotoc_md285',1,'']]],
  ['manager_20vcpkg_20default_20packagemanager_20cmake_20d9_20rationale_14',['7.9 D9 — Dual package manager, vcpkg default (&lt;span class=&quot;tt&quot;&gt;PackageManager.cmake&lt;/span&gt; + D9 rationale)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md37',1,'']]],
  ['managers_15',['20.7 Binary caching (both managers)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md126',1,'']]],
  ['mangad_20cpp_20project_20template_16',['3. The Original Repo: &lt;span class=&quot;tt&quot;&gt;MangaD/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md6',1,'']]],
  ['mangad_20v0_200_201_20→_20current_20v0_200_204_17',['6.4 Release asset delta (MangaD &lt;span class=&quot;tt&quot;&gt;v0.0.1&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;v0.0.4&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md25',1,'']]],
  ['manifest_20for_20github_20and_20gitlab_18',['3. One release manifest for GitHub and GitLab',['../md_docs_2TASKS.html#autotoc_md142',1,'']]],
  ['manifests_20must_20never_20leak_20into_20uploads_19',['7.3 D3 — Release inventory manifests must never leak into uploads',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md31',1,'']]],
  ['manjaro_20linux_20',['Arch Linux / Manjaro Linux',['../md_docs_2install.html#autotoc_md274',1,'']]],
  ['manual_20coverity_20adr_20004_21',['7.8 D8 — Manual Coverity (&lt;span class=&quot;tt&quot;&gt;ADR 004&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md36',1,'']]],
  ['manual_20install_20not_20recommended_20prefer_20vcpkg_22',['manual install not recommended prefer vcpkg',['../md_docs_2install.html#autotoc_md282',1,'Google Test (manual install not recommended, prefer vcpkg)'],['../md_docs_2install.html#autotoc_md281',1,'wxWidgets (manual install not recommended, prefer vcpkg)']]],
  ['math_23',['13.3 Inventory math',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md70',1,'']]],
  ['matrix_24',['matrix',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md56',1,'11.1 Q: What is the difference between &quot;CLANG&quot; and &quot;LLVM&quot; in the matrix?'],['../md_docs_2TASKS.html#autotoc_md190',1,'33. Cross-platform lifecycle matrix']]],
  ['matrix_20qa_25',['23. Full release-matrix QA',['../md_docs_2TASKS.html#autotoc_md172',1,'']]],
  ['maturity_20and_20long_20term_20maintenance_26',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md200',1,'']]],
  ['measurements_27',['19.2 Root causes, with measurements',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md109',1,'']]],
  ['merge_202026_2009_2028_28',['20.14 Consolidation, cleanup and merge (2026-09-28)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md133',1,'']]],
  ['merge_20notes_3a_20github_20copy_20gitlab_20copy_29',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md60',1,'']]],
  ['migration_30',['39. Release notes and migration',['../md_docs_2TASKS.html#autotoc_md198',1,'']]],
  ['mingw_31',['MinGW',['../md_docs_2install.html#autotoc_md279',1,'']]],
  ['mint_20ubuntu_32',['Debian / Linux Mint / Ubuntu',['../md_docs_2install.html#autotoc_md275',1,'']]],
  ['mode_20actually_20provisions_33',['What each CI mode actually provisions',['../md_docs_2install.html#autotoc_md290',1,'']]],
  ['msi_20lifecycle_34',['11. WiX MSI lifecycle',['../md_docs_2TASKS.html#autotoc_md152',1,'']]],
  ['msvc_35',['MSVC',['../md_docs_2development__guide.html#autotoc_md225',1,'MSVC'],['../md_docs_2install.html#autotoc_md278',1,'MSVC']]],
  ['must_20never_20leak_20into_20uploads_36',['7.3 D3 — Release inventory manifests must never leak into uploads',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md31',1,'']]],
  ['must_20not_20block_37',['Deferred (per issue §7, must not block)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md256',1,'']]]
];
