var searchData=
[
  ['gaps_0',['Remaining gaps',['../md_docs_2distribution-hardening-evidence.html#autotoc_md269',1,'']]],
  ['gate_1',['6. Release inventory gate',['../md_docs_2TASKS.html#autotoc_md145',1,'']]],
  ['gate_20—_20final_20acceptance_20checklist_2',['Release gate — final acceptance checklist',['../md_docs_2TASKS.html#autotoc_md213',1,'']]],
  ['gate_202_20pre_20flight_20vcpkg_3',['19.7 Gate 2 pre-flight (vcpkg)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md114',1,'']]],
  ['gates_4',['gates',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md116',1,'19.9 Release gates'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md131',1,'20.12 Release gates']]],
  ['gcc_20clang_5',['GCC / Clang',['../md_docs_2development__guide.html#autotoc_md224',1,'']]],
  ['getting_20started_6',['Getting Started',['../md_docs_2getting__started.html',1,'Getting Started'],['../index.html#autotoc_md310',1,'Getting Started']]],
  ['git_20tag_20reference_20integrity_7',['45. Git/tag/reference integrity',['../md_docs_2TASKS.html#autotoc_md207',1,'']]],
  ['github_8',['GitHub',['../md_docs_2development__guide.html#autotoc_md249',1,'']]],
  ['github_20actions_2011_20workflows_9',['8.2 GitHub Actions (11 workflows)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md47',1,'']]],
  ['github_20actions_20hardening_10',['30. GitHub Actions hardening',['../md_docs_2TASKS.html#autotoc_md185',1,'']]],
  ['github_20actions_20tips_11',['GitHub Actions tips',['../md_docs_2development__guide.html#autotoc_md234',1,'']]],
  ['github_20and_20gitlab_12',['3. One release manifest for GitHub and GitLab',['../md_docs_2TASKS.html#autotoc_md142',1,'']]],
  ['github_20copy_20gitlab_20copy_13',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md60',1,'']]],
  ['github_20gitlab_20copies_20into_20one_20repo_14',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md29',1,'']]],
  ['gitlab_15',['GitLab',['../md_docs_2TASKS.html#autotoc_md142',1,'3. One release manifest for GitHub and GitLab'],['../md_docs_2development__guide.html#autotoc_md250',1,'GitLab']]],
  ['gitlab_20as_20is_16',['12.4 Carried over from GitLab as-is',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md64',1,'']]],
  ['gitlab_20copies_20into_20one_20repo_17',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md29',1,'']]],
  ['gitlab_20copy_18',['12. Merge Notes: GitHub Copy + GitLab Copy',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md60',1,'']]],
  ['gitlab_20parity_20and_20security_19',['31. GitLab parity and security',['../md_docs_2TASKS.html#autotoc_md186',1,'']]],
  ['gitlab_20pipeline_20',['8.4 GitLab pipeline',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md49',1,'']]],
  ['gitlab_20tips_21',['GitLab tips',['../md_docs_2development__guide.html#autotoc_md236',1,'']]],
  ['google_20test_20manual_20install_20not_20recommended_20prefer_20vcpkg_22',['Google Test (manual install not recommended, prefer vcpkg)',['../md_docs_2install.html#autotoc_md282',1,'']]],
  ['governance_23',['governance',['../md_docs_2TASKS.html#autotoc_md187',1,'32. Repository governance'],['../md_docs_2TASKS.html#autotoc_md184',1,'P1 — CI/CD security and governance']]],
  ['graph_24',['2. Repository Lineage and Fork Graph',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md4',1,'']]],
  ['green_20yet_25',['Still runner/credential-dependent (cannot be claimed green yet)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md261',1,'']]],
  ['guarantees_20§6_20of_20the_20issue_20satisfied_26',['20.5 Isolation guarantees (§6 of the issue, satisfied)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md124',1,'']]],
  ['guide_27',['Guide',['../index.html#autotoc_md312',1,'Developer Guide'],['../md_docs_2development__guide.html',1,'Development Guide'],['../md_docs_2install.html',1,'Installation Guide']]],
  ['gz_20distribution_28',['P0 — Linux DEB/RPM/tar.gz distribution',['../md_docs_2TASKS.html#autotoc_md160',1,'']]]
];
