var searchData=
[
  ['objective_0',['13.1 Objective',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md68',1,'']]],
  ['observations_20found_20during_20inspection_1',['13.4 Bugs and observations found during inspection',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md71',1,'']]],
  ['of_20build_20truth_20adr_20001_2',['7.7 D7 — CMakePresets as the single source of build truth (&lt;span class=&quot;tt&quot;&gt;ADR 001&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md35',1,'']]],
  ['of_20decisions_3',['12.1 Summary of decisions',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md61',1,'']]],
  ['of_20done_4',['Definition of done',['../md_docs_2TASKS.html#autotoc_md137',1,'']]],
  ['of_20release_20workflows_20adr_20005_20ci_20yml_5',['7.2 D2 — Strict separation of release workflows (&lt;span class=&quot;tt&quot;&gt;ADR 005&lt;/span&gt; + &lt;span class=&quot;tt&quot;&gt;ci.yml&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md30',1,'']]],
  ['of_20scope_20unless_20separately_20justified_6',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md215',1,'']]],
  ['of_20the_20distribution_20hardening_20benchmark_202026_2009_2024_20→_202026_2009_2025_7',['17. Complete dated A→Z record of the distribution-hardening benchmark (2026-09-24 → 2026-09-25)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md92',1,'']]],
  ['of_20the_20issue_20satisfied_8',['20.5 Isolation guarantees (§6 of the issue, satisfied)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md124',1,'']]],
  ['of_20the_20original_9',['of the original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md9',1,'3.3 Engineering characteristics of the original'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md10',1,'3.4 Known limitations of the original']]],
  ['of_20the_20release_20path_10',['47. Security testing of the release path',['../md_docs_2TASKS.html#autotoc_md209',1,'']]],
  ['of_20upstream_20submission_11',['7.11 D11 — Opt-in CDash instead of upstream submission',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md39',1,'']]],
  ['offline_20and_20restricted_20network_20behavior_12',['34. Offline and restricted-network behavior',['../md_docs_2TASKS.html#autotoc_md191',1,'']]],
  ['offline_20validation_20every_20change_20before_20pushing_13',['19.5 Offline validation (every change, before pushing)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md112',1,'']]],
  ['offs_20visible_20from_20history_14',['4.3 Trade-offs visible from history',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md15',1,'']]],
  ['oldest_20first_15',['20.10 Commit timeline (all 29 commits, oldest first)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md129',1,'']]],
  ['omission_20pass_16',['P1 — Additional cross-cutting controls from the final omission pass',['../md_docs_2TASKS.html#autotoc_md205',1,'']]],
  ['on_20a_20v_20tag_20push_17',['8.3 Release flow (what happens on a &lt;span class=&quot;tt&quot;&gt;v*&lt;/span&gt; tag push)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md48',1,'']]],
  ['on_20main_2096240c0_18',['5.1 State on &lt;span class=&quot;tt&quot;&gt;main&lt;/span&gt; (&lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md18',1,'']]],
  ['on_20the_20repo_20itself_19',['7.15 D15 — OpenCode automations on the repo itself',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md43',1,'']]],
  ['on_20windows_20',['on Windows',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md62',1,'12.2 Static vs. dynamic CRT on Windows'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md38',1,'7.10 D10 — Static vs dynamic CRT on Windows']]],
  ['one_20home_20per_20key_21',['19.3 The fix — three tiers, one home per key',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md110',1,'']]],
  ['one_20release_20manifest_20for_20github_20and_20gitlab_22',['3. One release manifest for GitHub and GitLab',['../md_docs_2TASKS.html#autotoc_md142',1,'']]],
  ['one_20repo_23',['7.1 D1 — Absorb the divergent GitHub/GitLab copies into one repo',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md29',1,'']]],
  ['open_20items_24',['20.16 Residual limitations and open items',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md135',1,'']]],
  ['opencode_20automations_20on_20the_20repo_20itself_25',['7.15 D15 — OpenCode automations on the repo itself',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md43',1,'']]],
  ['operating_20rules_26',['17.1 Authoritative task, inputs and operating rules',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md93',1,'']]],
  ['operational_20maturity_20and_20long_20term_20maintenance_27',['P2 — Operational maturity and long-term maintenance',['../md_docs_2TASKS.html#autotoc_md200',1,'']]],
  ['operational_20view_28',['8. How the Project Works Now (Operational View)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md45',1,'']]],
  ['operator_20action_3a_20cache_20budget_29',['16.4 Operator action: cache budget',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md85',1,'']]],
  ['opt_20in_20cdash_20instead_20of_20upstream_20submission_30',['7.11 D11 — Opt-in CDash instead of upstream submission',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md39',1,'']]],
  ['order_31',['20.9 Bring-up: the failure loop, in order',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md128',1,'']]],
  ['original_32',['original',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md9',1,'3.3 Engineering characteristics of the original'],['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md10',1,'3.4 Known limitations of the original']]],
  ['original_2071cae18_20→_20current_2096240c0_33',['6.1 File inventory delta (original &lt;span class=&quot;tt&quot;&gt;71cae18&lt;/span&gt; → current &lt;span class=&quot;tt&quot;&gt;96240c0&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md22',1,'']]],
  ['original_20repo_3a_20mangad_20cpp_20project_20template_34',['3. The Original Repo: &lt;span class=&quot;tt&quot;&gt;MangaD/cpp-project-template&lt;/span&gt;',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md6',1,'']]],
  ['original_20vs_20current_35',['6. Comparative Deep-Dive: Original vs Current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md21',1,'']]],
  ['original_20vs_20current_36',['6.3 Workflow inventory: original vs current',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md24',1,'']]],
  ['out_37',['6.2 Source-level changes worth calling out',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md23',1,'']]],
  ['out_20of_20scope_20unless_20separately_20justified_38',['Explicitly out of scope unless separately justified',['../md_docs_2TASKS.html#autotoc_md215',1,'']]],
  ['output_39',['Validation results (commands → output)',['../md_docs_2distribution-hardening-evidence.html#autotoc_md260',1,'']]],
  ['over_20from_20bugs_20txt_40',['13.7 Residual follow-ups (carried over from &lt;span class=&quot;tt&quot;&gt;BUGS.txt&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md74',1,'']]],
  ['over_20from_20gitlab_20as_20is_41',['12.4 Carried over from GitLab as-is',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md64',1,'']]],
  ['owned_20by_20the_20current_20fork_20relative_20to_20naylacruz_20522bc3a_42',['5.2 Changes owned by the current fork (relative to NaylaCruz &lt;span class=&quot;tt&quot;&gt;522bc3a&lt;/span&gt;)',['../md_docs_2PROJECT__DOCUMENTATION.html#autotoc_md19',1,'']]]
];
