# cmake/PackageManager.cmake
#
# Selects between vcpkg and Conan 2 for this project's third-party
# dependencies (currently: wxWidgets, GTest), controlled by one variable so
# either can be used without editing this file:
#
#   vcpkg:   cmake -S . -B build -D PACKAGE_MANAGER=vcpkg \
#              -D CMAKE_TOOLCHAIN_FILE=<path-to-vcpkg>/scripts/buildsystems/vcpkg.cmake
#            (or use the `vcpkg-release` preset with VCPKG_ROOT exported)
#   conan2:  scripts/conan_install.sh --profile conan/profiles/<profile>
#            cmake --preset conan-release     (generated by CMakeUserPresets.json)
#            or, as CI does it: pass the generated toolchain explicitly --
#              -D PACKAGE_MANAGER=conan2
#              -D CMAKE_TOOLCHAIN_FILE=<output-folder>/generators/conan_toolchain.cmake
#   system:  -D PACKAGE_MANAGER=system  (host-provided packages; no toolchain)
#
# 2026-09-10: added per employer request -- support both, with Conan 2
# intended as the eventual default. Defaults to vcpkg FOR NOW: every CI
# config in this project (GitLab, both GitHub workflows, CircleCI) currently
# only provisions vcpkg, and switching the default here without that wiring
# in place would break every pipeline the moment this file lands, not add a
# new option. PACKAGE_MANAGER_DEFAULT below is the only line that needs to
# change once the release workflows can select Conan 2 (they do: see
# packaging/release-package-manager.txt + .github/workflows/release.yml).
#
# Both package managers are consumed the SAME way everywhere else in this
# project: through ordinary find_package(wxWidgets ...) / find_package(GTest
# ...) calls. Neither needs special-casing outside this file -- vcpkg's
# toolchain file and Conan's generated CMakeToolchain/CMakeDeps files both
# work by making find_package() resolve to their packages transparently.
# That's the whole reason this selection logic is isolated here instead of
# spreading `if(vcpkg) ... else() ...` branches through the rest of the
# build.
#
# Hardening (issue #152): a package-manager selection that cannot work is a
# configure-time error with an actionable message, not a warning that
# surfaces much later as a confusing find_package failure. Cross-manager
# mismatches (conan selected with a vcpkg toolchain, or vice versa) fail
# fast too -- mixing generated dependency metadata from two managers in one
# build tree is exactly the contamination this file exists to prevent.

set(PACKAGE_MANAGER_DEFAULT "vcpkg") # change to "conan2" once conan2 is selected for every CI path that needs it

set(PACKAGE_MANAGER "${PACKAGE_MANAGER_DEFAULT}" CACHE STRING
    "Which package manager provides third-party dependencies: vcpkg, conan2, or system")
set_property(CACHE PACKAGE_MANAGER PROPERTY STRINGS vcpkg conan2 system)

string(TOLOWER "${PACKAGE_MANAGER}" _pm)

set(_toolchain_is_vcpkg FALSE)
set(_toolchain_is_conan FALSE)
if(DEFINED CMAKE_TOOLCHAIN_FILE AND NOT CMAKE_TOOLCHAIN_FILE STREQUAL "")
    file(TO_CMAKE_PATH "${CMAKE_TOOLCHAIN_FILE}" _toolchain_cmake_path)
    if(_toolchain_cmake_path MATCHES "buildsystems/vcpkg\\.cmake$")
        set(_toolchain_is_vcpkg TRUE)
    elseif(_toolchain_cmake_path MATCHES "conan_toolchain\\.cmake$")
        set(_toolchain_is_conan TRUE)
    endif()
endif()

if(_pm STREQUAL "vcpkg")
    if(_toolchain_is_conan)
        message(FATAL_ERROR
            "PACKAGE_MANAGER=vcpkg but CMAKE_TOOLCHAIN_FILE points at a Conan "
            "toolchain:\n  ${CMAKE_TOOLCHAIN_FILE}\n"
            "Reconfigure with vcpkg's toolchain "
            "(<vcpkg>/scripts/buildsystems/vcpkg.cmake) or with "
            "PACKAGE_MANAGER=conan2. Do not mix toolchains from two package "
            "managers in one build tree.")
    endif()
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE OR NOT EXISTS "${CMAKE_TOOLCHAIN_FILE}")
        message(WARNING
            "PACKAGE_MANAGER=vcpkg but CMAKE_TOOLCHAIN_FILE is not set (or "
            "doesn't exist). It needs to point at vcpkg's "
            "scripts/buildsystems/vcpkg.cmake, passed with "
            "-D CMAKE_TOOLCHAIN_FILE=... on the configure command line -- "
            "the same way this project's existing CI already does it. The "
            "find_package() calls elsewhere in this project will fail "
            "without it.")
    endif()

elseif(_pm STREQUAL "system")
    # Use dependencies already provided by the host environment (for example
    # distro packages on Linux or MSYS2/Homebrew prefixes on other platforms).
    # No toolchain file is required; ordinary find_package() resolution is used.
    if(_toolchain_is_vcpkg OR _toolchain_is_conan)
        message(FATAL_ERROR
            "PACKAGE_MANAGER=system but CMAKE_TOOLCHAIN_FILE points at a "
            "package-manager toolchain:\n  ${CMAKE_TOOLCHAIN_FILE}\n"
            "Pass PACKAGE_MANAGER=vcpkg/conan2 to use it, or drop "
            "CMAKE_TOOLCHAIN_FILE to build against host-provided packages.")
    endif()

elseif(_pm STREQUAL "conan2")
    # Conan's generated toolchain file has to be produced and passed in
    # BEFORE this configure step runs -- CMAKE_TOOLCHAIN_FILE loads before
    # the rest of CMakeLists.txt is even processed, so this can only error
    # here if it's missing, not fix it retroactively.
    if(_toolchain_is_vcpkg)
        message(FATAL_ERROR
            "PACKAGE_MANAGER=conan2 but CMAKE_TOOLCHAIN_FILE points at vcpkg's "
            "toolchain:\n  ${CMAKE_TOOLCHAIN_FILE}\n"
            "Reconfigure without the vcpkg toolchain and with Conan's "
            "generated conan_toolchain.cmake instead. Do not mix toolchains "
            "from two package managers in one build tree.")
    endif()
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE OR NOT EXISTS "${CMAKE_TOOLCHAIN_FILE}")
        message(FATAL_ERROR
            "PACKAGE_MANAGER=conan2 but CMAKE_TOOLCHAIN_FILE is not set (or "
            "doesn't exist).\n"
            "Provision the dependencies first, from the source root:\n"
            "  scripts/conan_install.sh --profile conan/profiles/<profile>\n"
            "which generates (default output folder build/conan2):\n"
            "  build/conan2/build/<BuildType>/generators/conan_toolchain.cmake\n"
            "then configure with:\n"
            "  -D PACKAGE_MANAGER=conan2\n"
            "  -D CMAKE_TOOLCHAIN_FILE=<that path>\n"
            "(or `cmake --preset conan-release` after "
            "`conan install . -of build/conan2 -pr <profile>`, which sets "
            "both). The find_package() calls elsewhere in this project will "
            "fail without it.")
    endif()
    if(NOT _toolchain_is_conan)
        message(WARNING
            "PACKAGE_MANAGER=conan2 but CMAKE_TOOLCHAIN_FILE does not look "
            "like a Conan-generated toolchain (expected a file named "
            "conan_toolchain.cmake):\n  ${CMAKE_TOOLCHAIN_FILE}\n"
            "Continuing as requested; if find_package() resolves unexpected "
            "packages, check that the toolchain came from `conan install`.")
    endif()

else()
    message(FATAL_ERROR
        "PACKAGE_MANAGER must be 'vcpkg', 'conan2', or 'system', got: '${PACKAGE_MANAGER}'. "
        "Set it with -D PACKAGE_MANAGER=vcpkg, -D PACKAGE_MANAGER=conan2, or "
        "-D PACKAGE_MANAGER=system.")
endif()

message(STATUS "Package manager: ${PACKAGE_MANAGER}")
