name: Clear all Github actions caches

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-24.04
    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@9e4f7c0f13c90041801b573939088eb9176d0220 # v2
